/*
 * File: app/view/GelBlasterPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GelBlaster.view.GelBlasterPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.gelblasterpanel',

    requires: [
        'GelBlaster.view.GelBlasterPanelViewModel',
        'Ext.Panel',
        'Ext.Button',
        'Ext.field.Slider',
        'Ext.field.Number',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    viewModel: {
        type: 'gelblasterpanel'
    },
    fullscreen: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            itemId: 'tabControls',
            scrollable: true,
            title: 'Controls',
            items: [
                {
                    xtype: 'container',
                    itemId: 'steering',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'mybutton8',
                            margin: '10 0 0 10',
                            text: 'Virtual Controller',
                            listeners: {
                                tap: 'onMybutton8Tap'
                            }
                        },
                        {
                            xtype: 'container',
                            userCls: 'steering-label',
                            margin: 5,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    html: 'Left',
                                    margin: '0 0 0 60'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    html: 'Right'
                                }
                            ]
                        },
                        {
                            xtype: 'sliderfield',
                            bind: '{steeringSetValue}',
                            itemId: 'steeringSetPointSlider',
                            name: 'steeringSlider',
                            margin: '0 10 5 10',
                            label: 'Steer',
                            labelWidth: 65,
                            value: 500,
                            liveUpdate: true,
                            maxValue: 1000
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'throttle',
                    items: [
                        {
                            xtype: 'container',
                            userCls: 'steering-label',
                            margin: 5,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    html: 'Reverse',
                                    margin: '0 0 0 60'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    html: 'Forward'
                                }
                            ]
                        },
                        {
                            xtype: 'sliderfield',
                            bind: '{throttleSetValue}',
                            itemId: 'throttleSlider',
                            name: 'throttleSlider',
                            margin: '0 10 5 10',
                            label: 'Throttle',
                            labelWidth: 65,
                            value: 50,
                            liveUpdate: true,
                            maxValue: 1000
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 't-rex pan',
                    items: [
                        {
                            xtype: 'container',
                            userCls: 'steering-label',
                            margin: 5,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    html: 'Left',
                                    margin: '0 0 0 60'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    html: 'Right'
                                }
                            ]
                        },
                        {
                            xtype: 'sliderfield',
                            bind: '{trexPanSetValue}',
                            itemId: 'trexPanSlider',
                            name: 'trexPanSlider',
                            margin: '0 10 5 10',
                            label: 'Pan',
                            labelWidth: 68,
                            value: 500,
                            liveUpdate: true,
                            maxValue: 1000,
                            listeners: {
                                change: 'onTrexPanSliderChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 't-rex tilt',
                    items: [
                        {
                            xtype: 'container',
                            userCls: 'steering-label',
                            margin: 5,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    html: 'Down',
                                    margin: '0 0 0 60'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    html: 'Up'
                                }
                            ]
                        },
                        {
                            xtype: 'sliderfield',
                            bind: '{trexTiltSetValue}',
                            itemId: 'trexTiltSlider',
                            name: 'trexTiltSlider',
                            margin: '0 10 5 10',
                            label: 'Tilt',
                            labelWidth: 65,
                            value: 500,
                            liveUpdate: true,
                            maxValue: 1000,
                            listeners: {
                                change: 'onTrexTiltSliderChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 't-rex jaw',
                    items: [
                        {
                            xtype: 'container',
                            userCls: 'steering-label',
                            margin: 5,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    html: 'Close',
                                    margin: '0 0 0 60'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    html: 'Open'
                                }
                            ]
                        },
                        {
                            xtype: 'sliderfield',
                            bind: '{trexJawSetValue}',
                            itemId: 'trexJawSlider',
                            name: 'trexJawSlider',
                            margin: '0 10 5 10',
                            label: 'Slider',
                            labelWidth: 65,
                            value: 0,
                            liveUpdate: true,
                            maxValue: 1000,
                            listeners: {
                                change: 'onTrexJawSliderChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'hbox',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'ThrottleHbox',
                            userCls: 'variable-box',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'throttleLabel',
                                    html: 'Throttle',
                                    margin: 10
                                },
                                {
                                    xtype: 'numberfield',
                                    bind: '{throttleSetValue}',
                                    itemId: 'throttleText',
                                    width: 100,
                                    margin: 10,
                                    label: 'set',
                                    labelWidth: 35,
                                    value: 0,
                                    clearable: false,
                                    maxValue: 1000,
                                    minValue: 0,
                                    listeners: {
                                        change: 'onThrottleTextChange'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'shootLabel',
                                    html: 'Shoot',
                                    margin: 10
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'shootText',
                                    width: 100,
                                    margin: 10,
                                    label: 'set',
                                    labelWidth: 35,
                                    value: 0,
                                    clearable: false,
                                    maxValue: 1000,
                                    minValue: 0,
                                    listeners: {
                                        change: 'onShootTextChange'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'setPointHbox',
                            userCls: 'variable-box',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'setPointActualLabel',
                                    html: 'Steer Set & Actual',
                                    margin: 10
                                },
                                {
                                    xtype: 'numberfield',
                                    bind: '{steeringSetValue}',
                                    itemId: 'steeringSetPointText',
                                    width: 120,
                                    margin: 10,
                                    label: 'set point',
                                    labelWidth: 70,
                                    value: 50,
                                    clearable: false,
                                    maxValue: 1000,
                                    minValue: 0,
                                    listeners: {
                                        change: 'onSteeringSetPointTextChange'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'steeringCurrent',
                                    width: 120,
                                    margin: 10,
                                    label: 'current',
                                    labelWidth: 70,
                                    value: 0,
                                    clearable: false
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'pidError',
                                    width: 120,
                                    margin: 10,
                                    label: 'error',
                                    labelWidth: 70,
                                    value: 0,
                                    clearable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'pidHbox',
                            userCls: 'variable-box',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'pidVariablesLabel',
                                    html: 'PID Constants',
                                    margin: 10
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'pidConstantP',
                                    width: 80,
                                    margin: 10,
                                    label: 'P',
                                    labelWidth: 25,
                                    value: 0,
                                    clearable: false,
                                    decimals: 3
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'pidConstantI',
                                    width: 80,
                                    margin: 10,
                                    label: 'I',
                                    labelWidth: 25,
                                    value: 0,
                                    clearable: false,
                                    decimals: 3
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'pidConstantD',
                                    width: 80,
                                    margin: '10 10 0 10',
                                    label: 'D',
                                    labelWidth: 25,
                                    value: 0,
                                    clearable: false,
                                    decimals: 3
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'updatePidConstants',
                                    margin: '10 10 10 30',
                                    text: 'Update',
                                    listeners: {
                                        tap: 'onMybutton1Tap'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'buttonsHbox',
                            userCls: 'variable-box',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'buttonsLabel',
                                    html: 'Control',
                                    margin: 10
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 5 20',
                                    text: 'Stop Steering',
                                    listeners: {
                                        tap: 'onMybuttonTap'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '5 20 5 20',
                                    text: 'Stop Throttle',
                                    listeners: {
                                        tap: 'onMybuttonTap2'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '5 20 5 20',
                                    text: 'Stop Steer Loop',
                                    listeners: {
                                        tap: 'onMybuttonTap1'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '5 20 5 20',
                                    text: 'Start Steer Loop',
                                    listeners: {
                                        tap: 'onMybuttonTap11'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'gamepadHbox',
                            userCls: 'variable-box',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'gamepadLabel',
                                    html: 'Gamepad',
                                    margin: 10
                                },
                                {
                                    xtype: 'container',
                                    margin: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'start'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            clearIcon: false,
                                            itemId: 'gamepadRightX',
                                            width: 95,
                                            margin: '0 0 0 2',
                                            label: 'R X',
                                            labelWidth: 28,
                                            clearable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            clearIcon: false,
                                            itemId: 'gamepadRightY',
                                            width: 85,
                                            margin: '0 2 0 2',
                                            label: 'Y',
                                            labelWidth: 16,
                                            clearable: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'start'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            clearIcon: false,
                                            itemId: 'gamepadLeftX',
                                            width: 95,
                                            margin: '0 0 0 2',
                                            label: 'L X',
                                            labelWidth: 28,
                                            clearable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            clearIcon: false,
                                            itemId: 'gamepadLeftY',
                                            width: 85,
                                            margin: '0 2 0 2',
                                            label: 'Y',
                                            labelWidth: 16,
                                            clearable: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'gamepadFwd',
                                    width: 120,
                                    margin: 10,
                                    label: 'Tr',
                                    labelWidth: 40,
                                    clearable: false,
                                    maxValue: 100,
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    itemId: 'gamepadRev',
                                    width: 120,
                                    margin: 10,
                                    label: 'Tl',
                                    labelWidth: 40,
                                    clearable: false,
                                    maxValue: 100,
                                    minValue: 0
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'buttonsHbox1',
                            userCls: 'variable-box',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'soundButtonsLabel',
                                    html: 'Sounds',
                                    margin: 10
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 5 20',
                                    text: 'X: T Rex',
                                    listeners: {
                                        tap: 'onMybuttonTap3'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '5 20 5 20',
                                    text: 'Y: Next Sound',
                                    listeners: {
                                        tap: 'onMybuttonTap21'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'serialCommandHbox',
                            userCls: 'variable-box',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'serialCommandsLabel',
                                    html: 'Arduino Command',
                                    margin: 10
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'arduinoCommand',
                                    width: 120,
                                    margin: 10,
                                    clearable: false
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 5 20',
                                    text: 'Send',
                                    listeners: {
                                        tap: 'onMybuttonTap31'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    html: '<u>LEDS:</u><BR>1-4 solid colors<BR>5-8 blik<BR><u>Text</u><BR>t1Hello World<BR>&nbsp;&nbsp;&nbsp;on line 1 show Hello World'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'debugOutputLabel',
                    html: 'Debug Output',
                    margin: 10
                },
                {
                    xtype: 'cartesian',
                    height: 250,
                    hidden: false,
                    itemId: 'steeringChart',
                    animation: false,
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    bind: {
                        store: '{steeringChartStore}'
                    },
                    axes: [
                        {
                            type: 'numeric',
                            grid: {
                                odd: {
                                    fill: '#e8e8e8'
                                }
                            },
                            maximum: 1100,
                            minimum: -100,
                            position: 'left',
                            title: 'Position'
                        }
                    ],
                    series: [
                        {
                            type: 'line',
                            colors: [
                                'rgba(200,0,0,0.3)'
                            ],
                            style: {
                                stroke: 'rgb(200,0,0)',
                                step: true
                            },
                            xField: 'x',
                            yField: 'steeringCurrent'
                        },
                        {
                            type: 'line',
                            colors: [
                                'rgba(0,200,0,0.3)'
                            ],
                            style: {
                                stroke: 'rgb(0,200,0)',
                                step: true
                            },
                            xField: 'x',
                            yField: 'steeringTargetPoint'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 240,
                    itemId: 'debugOutputContainerOuter',
                    userCls: 'debugOutputContainer',
                    margin: 10,
                    scrollable: 'vertical',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'debugOutputContainer'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            itemId: 'tabVideo',
            layout: 'vbox',
            title: 'Video',
            items: [
                {
                    xtype: 'container',
                    padding: 10,
                    defaults: {
                        margin: '0 0 0 10',
                        height: 50
                    },
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'videoStatus',
                            width: 150,
                            html: 'Status',
                            padding: '20 0 0 0'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnView',
                            width: 120,
                            text: 'Start Video',
                            listeners: {
                                tap: 'onBtnViewTap'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnStop',
                            width: 120,
                            text: 'Stop Video',
                            listeners: {
                                tap: 'onBtnStopTap'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnStartTargets',
                            width: 120,
                            text: 'Start Targets',
                            listeners: {
                                tap: 'onBtnStartTargetsTap'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnStartTimer',
                            width: 100,
                            text: 'Start Timer',
                            listeners: {
                                tap: 'onBtnStartTimerTap'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnStopTimer',
                            width: 100,
                            text: 'Stop Timer',
                            listeners: {
                                tap: 'onBtnStopTimerTap'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '100%',
                    userCls: 'video-parent',
                    html: '<canvas id="video-canvas" class="video"></canvas>'
                }
            ]
        }
    ],
    listeners: {
        painted: 'onFormpanelPainted',
        activeItemchange: 'onTabpanelActiveItemChange'
    },

    onMybutton8Tap: function(button, e, eOpts) {
        this.showVirtualController();
    },

    onTrexPanSliderChange: function(me, newValue, oldValue, eOpts) {
        if(newValue && newValue.constructor === Array){
            newValue = newValue[0];
        }
        this.websocketSend(Ext.encode({
            action:'setPan',
            value:newValue
        }));
    },

    onTrexTiltSliderChange: function(me, newValue, oldValue, eOpts) {
        if(newValue && newValue.constructor === Array){
            newValue = newValue[0];
        }
        this.websocketSend(Ext.encode({
            action:'setTilt',
            value:newValue
        }));
    },

    onTrexJawSliderChange: function(me, newValue, oldValue, eOpts) {
        if(newValue && newValue.constructor === Array){
            newValue = newValue[0];
        }

        this.websocketSend(Ext.encode({
            action:'updateTrexJaw',
            value:newValue
        }));
    },

    onThrottleTextChange: function(field, newValue, oldValue, eOpts) {
        if(newValue && newValue.constructor === Array){
            newValue = newValue[0];
        }

        this.moveX = newValue;

        this.websocketSend(Ext.encode({
            action:'move',
            x:this.moveX,
            y:this.moveY
        }));
    },

    onShootTextChange: function(field, newValue, oldValue, eOpts) {
        if(newValue && newValue.constructor === Array){
            newValue = newValue[0];
        }

        this.websocketSend(Ext.encode({
            action:'setShoot',
            value:newValue
        }));
    },

    onSteeringSetPointTextChange: function(field, newValue, oldValue, eOpts) {
        if(newValue && newValue.constructor === Array){
            newValue = newValue[0];
        }

        if(!this.lastSteeringChangeDefered){
            this.lastSteeringChangeDefered = true;

            if(this.lastSent != newValue){
                this.sendUpdateSteering(newValue);
                this.lastSent = newValue;
            }
            Ext.defer(function(){
                this.lastSteeringChangeDefered = false;
                var currentValue = field.getValue();

                if(this.lastSent != currentValue){
                    this.lastSent = currentValue;
                    this.sendUpdateSteering(currentValue);
                }
            },2,this);
        }
    },

    onMybutton1Tap: function(button, e, eOpts) {
        var p = this.queryById('pidConstantP').getValue(),
            i = this.queryById('pidConstantI').getValue(),
            d = this.queryById('pidConstantD').getValue();

        if(p === null || i === null || d === null){
            Ext.Msg.alert(' ','Invalid Constants! Please try again!');
            return false;
        }
        this.websocketSend(Ext.encode({
            action:'updatePidConstants',
            p: p,
            i: i,
            d: d
        }));
    },

    onMybuttonTap: function(button, e, eOpts) {
        this.stopSteeringMovement();
    },

    onMybuttonTap2: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'stopThrottle'
        }));
    },

    onMybuttonTap1: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'stopSteeringControlLoop'
        }));
    },

    onMybuttonTap11: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'startSteeringControlLoop'
        }));
    },

    onMybuttonTap3: function(button, e, eOpts) {
        this.trexscream();
    },

    onMybuttonTap21: function(button, e, eOpts) {
        this.playnextsound();
    },

    onMybuttonTap31: function(button, e, eOpts) {
        var arduinoCommand = this.queryById('arduinoCommand');

        var command = arduinoCommand.getValue();
        if(command == ''){
            Ext.Msg.alert(' ','Please enter an Arduino Command');
            return;
        }

        this.websocketSend(Ext.encode({
            action:'arduinoCommand',
            command:command
        }));

    },

    onBtnViewTap: function(button, e, eOpts) {
        this.startVideo();
    },

    onBtnStopTap: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'stopVideo'
        }));
    },

    onBtnStartTargetsTap: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'startTargets'
        }));
    },

    onBtnStartTimerTap: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'startTargetTimer'
        }));
    },

    onBtnStopTimerTap: function(button, e, eOpts) {
        this.websocketSend(Ext.encode({
            action:'stopTargetTimer'
        }));
    },

    onFormpanelPainted: function(sender, element, eOpts) {
        this.webSocketCon = null;
        this.websocketOpen();

        this.gamepadInit();

        this.trexPanSlider = this.queryById('trexPanSlider');
        this.trexTiltSlider = this.queryById('trexTiltSlider');

        //this.fieldGamepadLeftRight = this.queryById('gamepadRightLeft');
        //this.fieldGamepadFwd = this.queryById('gamepadFwd');
        //this.fieldGamepadRev = this.queryById('gamepadRev');

        this.fieldGamepadRightX = this.queryById('gamepadRightX');
        this.fieldGamepadRightY = this.queryById('gamepadRightY');

        this.fieldGamepadLeftX = this.queryById('gamepadLeftX');
        this.fieldGamepadLeftY = this.queryById('gamepadLeftY');

        this.fieldSteeringSetPointText = this.queryById('steeringSetPointText');
        this.fieldThrottleText = this.queryById('throttleText');

        this.fieldShootText = this.queryById('shootText');

        this.wsLeftStickX = -1;
        this.wsLeftStickY = -1;
        this.wsRightStickX = -1;
        this.wsRightStickY = -1;
        this.wsTriggerRight = -1;


    },

    onTabpanelActiveItemChange: function(sender, value, oldValue, eOpts) {
        switch(value.getItemId()){
            case 'tabVideo':
                this.startVideo();
        }
    },

    trexscream: function() {
        this.websocketSend(Ext.encode({
            action:'trexscream'
        }));
    },

    playnextsound: function() {
        this.websocketSend(Ext.encode({
            action:'playnextsound'
        }));
    },

    websocketSend: function(message) {
        if(this.webSocketCon === null || this.webSocketCon.readyState !== WebSocket.OPEN){
            console.log('Sending to WebSocket failed - not connected');
            return false;
        }

        this.webSocketCon.send(message);
    },

    websocketOpen: function() {
            if(this.webSocketCon !== null &&
               ( this.webSocketCon.readyState === WebSocket.CONNECTING ||
                this.webSocketCon.readyState === WebSocket.OPEN )
            ){
                //if the socket is already open, or connecting. dont open more than 1
                this.appendDebugOutput("Websocket already open or connecting");
                return;
            }

            this.appendDebugOutput("Opening Websocket");

            try{
                this.webSocketCon = new WebSocket('ws://'+window.location.host+'/wsapi');
            }catch(err){
                this.appendDebugOutput("Exception opening socket!");
                this.appendDebugOutput(err.message);
                this.webSocketCon = null;
                return false;
            }

        	this.webSocketCon.onopen = function(){
                this.websocketSend(Ext.encode({
                    action:'getStatus'
                }));
        	}.bind(this);

        	this.webSocketCon.onmessage = this.websocketReceive.bind(this);

        	this.webSocketCon.onerror = function(event){
        		this.appendDebugOutput("error with websocket! " + event.error);

                this.webSocketCon = null;
                this.websocketReconnect();
        	}.bind(this);

        	this.webSocketCon.onclose = function(event){
        		this.appendDebugOutput("websocket closed! "+event.code+" "+event.reason);

                this.webSocketCon = null;
                this.websocketReconnect();
        	}.bind(this);


    },

    websocketReconnect: function() {
        Ext.defer(function(){ this.websocketOpen(); },500,this);
    },

    websocketReceive: function(message) {
        // console.log('recieved message');
        // console.log(message.data);
        //this.appendDebugOutput('recieved message: '+message.data);


        var jsonData = JSON.parse(message.data);

        if(!jsonData.cmd){
            console.log('Missing cmd!');
            console.log(jsonData);
            return false;
        }
        switch(jsonData.cmd){
            default:
                console.log('Invalid cmd!');
                console.log(jsonData);
                break;
            case 'status':
                this.msgUpdateStatus(jsonData);
                break;
            case 'pidConstants':
                this.msgUpdatePidConstants(jsonData);
                break;
            case 'videoRunning':
                this.checkVideoRunningResponse(jsonData);
                break;
        }


    },

    stopSteeringMovement: function() {
        this.websocketSend(Ext.encode({
            action:'stopSteeringMovement'
        }));
    },

    sendUpdateSteering: function(value) {
        this.moveY = value;

        this.websocketSend(Ext.encode({
            //action:'setSteering',
            action:'move',
            y:this.moveY,
            x:this.moveX
        }));
    },

    msgUpdateStatus: function(jsonData) {
        // this.recievedMessages++;
        this.chartedMessages++;


        // if(this.recievedMessages > 100){
        //     this.recievedMessages = 0;
        //     this.clearDebugOutput();
        //     //chartStore.removeAll();
        // }



        if(this.chartStore.count() > 100){
            this.chartStore.removeAt(0,1);
        }

        //this.steeringChart.suspendAnimation();
        // if(this.chartArray.length > 100){
        //     this.chartArray.shift();
        // }
        // this.chartArray.push([this.chartedMessages, jsonData.steeringCurrent, jsonData.steeringTargetPoint]);

        // this.chartStore.loadData(this.chartArray);

        this.chartStore.loadData([[this.chartedMessages, jsonData.steeringCurrent, jsonData.steeringTarget]], true);

        //this.steeringChart.resumeAnimation();

        this.queryById('steeringCurrent').setValue(jsonData.steeringCurrent);
        this.queryById('pidError').setValue(jsonData.pidError);
    },

    msgUpdatePidConstants: function(jsonData) {
        this.queryById('pidConstantP').setValue(jsonData.p);
        this.queryById('pidConstantI').setValue(jsonData.i);
        this.queryById('pidConstantD').setValue(jsonData.d);
    },

    gamepadInit: function() {
        window.addEventListener("gamepadconnected", this.gamepadConnected.bind(this));
        window.addEventListener("gamepaddisconnected", this.gamepadDisconnected.bind(this));

    },

    gamepadConnected: function(e) {
        console.log("gamepad connected");
        console.log(e);

        this.appendDebugOutput("Gamepad connected at index "+e.gamepad.index+", id "+e.gamepad.id+". "+e.gamepad.buttons.length+" buttons, "+e.gamepad.axes.length+" axes");


        if(e.gamepad.id.indexOf('Xbox') !== -1){
            this.gamepadBeginLoop(e.gamepad);
        }else{
            this.appendDebugOutput("Not an xbox controller. Skipping!");
        }
    },

    gamepadDisconnected: function(e) {

            console.log("gamepad disconnected");
            console.log(e);

            this.appendDebugOutput("Gamepad disconnected at index "+e.gamepad.index+", id "+e.gamepad.id);

            clearInterval(this.gamePadLoops[e.gamepad.id]['loop']);
    },

    gamepadBeginLoop: function(gamepad) {
        if(!this.gamePadLoops){
            this.gamePadLoops = {};
        }

        if(this.gamePadLoops[gamepad.id]){
            return;
        }
        this.gamePadLoops[gamepad.id] = {
            gamepad:gamepad
        };

        this.gamePadLoops[gamepad.id]['loop'] = setInterval(this.gamepadUpdate.bind(this), 50, gamepad);

    },

    gamepadUpdate: function(gamepad) {
        //console.log('gamepadUpdate');

        var gamepadUpdate = navigator.getGamepads();

        if(gamepadUpdate[gamepad.index]){
            gamepad = gamepadUpdate[gamepad.index];
        }else{
            console.log('gamepad no longer available?');
            clearInterval(this.gamePadLoops[e.gamepad.id]['loop']);
            return;
        }
        //console.log(gamepad);

        //console.log('Fwd: '+gamepad.buttons[7].value);
        //console.log('Rev: '+gamepad.buttons[6].value);

        //console.log('Right: '+gamepad.axes[2]);

        //X button
        if(gamepad.buttons[2].value == 1 && this.button2lastValue != gamepad.buttons[2].value){
            this.trexscream();
        }
        this.button2lastValue = gamepad.buttons[2].value;

        //Y button
        if(gamepad.buttons[3].value == 1 && this.button3lastValue != gamepad.buttons[3].value){
            this.playnextsound();
        }
        this.button3lastValue = gamepad.buttons[3].value;


        var leftStickX = gamepad.axes[0] - .08;
        this.fieldGamepadLeftX.setValue(leftStickX);
        var leftStickXslider = Math.round((leftStickX * 500) + 500);
        if(leftStickXslider !== this.wsLeftStickX ){
            this.wsLeftStickX = leftStickXslider;
            this.fieldSteeringSetPointText.setValue(leftStickXslider);
        }

        var leftStickY = gamepad.axes[1];
        this.fieldGamepadLeftY.setValue(leftStickY);
        var leftStickYslider = 1000 - Math.round((leftStickY * 500) + 500);
        if(leftStickYslider !== this.wsLeftStickY ){
            this.wsLeftStickY = leftStickYslider;
            this.fieldThrottleText.setValue(leftStickYslider);
        }

        var rightStickX = gamepad.axes[2];
        this.fieldGamepadRightX.setValue(rightStickX);
        var rightStickXslider = 1000 - Math.round((rightStickX * 500) + 500);
        if(rightStickXslider !== this.wsRightStickX ){
            this.wsRightStickX = rightStickXslider;
            this.trexPanSlider.setValue(rightStickXslider);
        }


        var rightStickY = gamepad.axes[3];
        this.fieldGamepadRightY.setValue(rightStickY);
        var rightStickYslider = Math.round((rightStickY * 500) + 500);
        if(rightStickYslider !== this.wsRightStickY ){
            this.wsRightStickY = rightStickYslider;
            this.trexTiltSlider.setValue(rightStickYslider);
        }

        var triggerRight = gamepad.buttons[7].value;
        //this.fieldGamepadFwd.setValue(triggerRight);

        var triggerLeft = gamepad.buttons[6].value;
        //this.fieldGamepadRev.setValue(triggerLeft);


        if(triggerRight >= 0.8){
            triggerRight = 1;
        }else{
            triggerRight = 0;
        }
        if(triggerRight !== this.wsTriggerRight ){
            this.wsTriggerRight = triggerRight;
            this.fieldShootText.setValue(triggerRight);
        }

        if(this.virtualController){
            var vsRx = rightStickX * 50;
            var vsRy = rightStickY * 50;
            var vsLx = leftStickX * 50;
            var vsLy = leftStickY * 50;

            //console.log(vsRx, vsRy, vsLx, vsLy);
            this.virtualControllerStickRight.stick.style.transform = `translate3d(${vsRx}px, ${vsRy}px, 0px)`;
            this.virtualControllerStickLeft.stick.style.transform = `translate3d(${vsLx}px, ${vsLy}px, 0px)`;

            if(triggerRight > 0){
                this.virtualControllerbuttonFire.classList.add("pressed");
            }else{
                this.virtualControllerbuttonFire.classList.remove("pressed");
            }
        }
    },

    showVirtualController: function() {
        if(!this.virtualController){
            this.virtualController = Ext.create({
                xtype:'panel',
                title:'Virtual Controller',
                floated:true,
                userCls:'controller-window',
                width:500,
                height:300,
                x:150,
                y:100,
                closable:true,
                closeAction:'hide',
                draggable:true,
                html:'<div class="button-container"><div class="left-buttons">'+
        		'<div class="stick" id="virctrlstickLeft"></div>'+
        		'<button class="btn-fire" id="virctrlbuttonFire"></button>'+
        	'</div>'+
        	'<div class="right-buttons">'+
        		'<div class="stick" id="virctrlstickRight"></div>'+
        	'</div></div>',
                listeners:{
                    scope:this,
                    painted:function(){
                        console.log(this);
                        if(!this.buttonsInit){
                            this.buttonsInit = true;
                            this.virtualControllerbuttonFire = document.getElementById('virctrlbuttonFire');
                            createFireButton(this.virtualControllerbuttonFire, function(state){
                                console.log('fire button!', state);
                                if(state==='down'){
                                    this.fieldShootText.setValue(1);
                                }else if(state==='up'){
                                    this.fieldShootText.setValue(0);
                                }

                            }.bind(this));
                            stickRange = 50;
                            this.virtualControllerStickRight = createStick(document.getElementById('virctrlstickRight'), stickRange, 'right', function(pos){
                                console.log('stick move! right ', pos);
                                this.fieldGamepadRightX.setValue(pos.x);
                                this.fieldGamepadRightY.setValue(pos.y);

                                var x = 1000 - Math.round(((pos.x/50) * 500) + 500);
                                var y = Math.round(((pos.y/50) * 500) + 500);
                                this.trexPanSlider.setValue(x);
                                this.trexTiltSlider.setValue(y);
                            }.bind(this));
                            this.virtualControllerStickLeft = createStick(document.getElementById('virctrlstickLeft'), stickRange, 'left', function(pos){
                                console.log('stick move! left ', pos);

                                this.fieldGamepadLeftX.setValue(pos.x);
                                this.fieldGamepadLeftY.setValue(pos.y);

                                var x = Math.round(((pos.x/50) * 500) + 500);
                                var y = 1000 - Math.round(((pos.y/50) * 500) + 500);
                                this.fieldSteeringSetPointText.setValue(x);
                                this.fieldThrottleText.setValue(y);
                            }.bind(this));
                        }
                    }
                }
            });

        }
        console.log(this.virtualController);
        this.virtualController.show({type:'slide', direction:'right'});

    },

    clearDebugOutput: function() {
        // console.log(message);
        // console.log(this.queryById('debugOutputContainer'));
        var dom = this.queryById('debugOutputContainer').el.dom;
        // console.log(dom);
        dom.innerHTML = "";
    },

    appendDebugOutput: function(message) {
        console.log(message);

        // console.log(this.queryById('debugOutputContainer'));
        var dom = this.queryById('debugOutputContainer').el.dom;
        // console.log(dom);
        dom.innerHTML += message + "<BR>\r\n";
        // console.log(this.queryById('debugOutputContainerOuter'));
        containerDom = this.queryById('debugOutputContainerOuter').bodyElement.dom;
        containerDom.scrollTop = dom.clientHeight;
    },

    startVideo: function() {
        if(!this.YesCheckingVideoRunning){
            this.YesCheckingVideoRunning = true;
            this.checkVideoRunning();
        }

        this.websocketSend(Ext.encode({
            action:'startVideo'
        }));

        if(!this.videoStreamPlayer){
            var canvas = document.getElementById('video-canvas');
            var url = 'ws://'+document.location.hostname+':8080/viewVideo';
            this.videoStreamPlayer = new JSMpeg.Player(url, {canvas: canvas});
        }
    },

    checkVideoRunning: function() {
        this.websocketSend(Ext.encode({
            action:'readVideoRunning'
        }));

        if(this.YesCheckingVideoRunning){
            Ext.defer(function(){
                this.checkVideoRunning();
            }, 1000, this);
        }
    },

    checkVideoRunningResponse: function(response) {
        this.YesCheckingVideoRunning = response.running;
        this.queryById('videoStatus').setHtml('Status: ' + (response.running ? 'Running' : 'Stopped'));
    }

});